

networks:
  umschool_network:

services:

  postgres:
    image: postgres:15-alpine
    restart: "no"  # избавляемся от автоматической перезагрузки
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      # Superuser username/password
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: data
    volumes:
      - "01-simple-alchemy-postgres:/var/lib/postgresql/data"
    networks:
      - umschool_network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: "no"
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - "01-simple-alchemy-pgadmin:/var/lib/pgadmin"
    depends_on:
      - postgres
    networks:
      - umschool_network


  aiogram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: alembic upgrade head && python main.py
    restart: "no"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - umschool_network

volumes:
  01-simple-alchemy-pgadmin:
  01-simple-alchemy-postgres: